"""
augment_data.py — supplement the Kaggle medical-symptom phrases with nurse-call
phrases for the 5 intents the Kaggle set doesn't cover (Food/Water, Mobility,
Hygiene, Information, Other), plus reinforcement examples for the weaker classes.

The Kaggle "Medical Speech" dataset only contains symptom descriptions, which map
to Pain / Emergency / Medication / Emotional Support. A real nurse-call system needs
all 9 intents, so we add curated, paraphrased phrases for full taxonomy coverage.

These are hand-written templates reflecting how patients actually phrase requests.
"""

# intent -> list of natural patient phrasings
AUGMENTATION = {
    "Food/Water": [
        "i am hungry can i get something to eat",
        "could i please have a glass of water",
        "i am really thirsty",
        "when is my next meal coming",
        "can i get some water please",
        "i would like some food",
        "my mouth is dry i need water",
        "is it time for lunch yet",
        "i did not get my breakfast",
        "please bring me something to drink",
        "i want to eat something",
        "can i have juice instead of water",
        "i feel hungry it has been hours",
        "may i have a snack",
        "i need water to take with my food",
        "the water jug is empty please refill it",
        "i am starving when is dinner",
        "could you get me some warm water",
        "i haven't eaten anything all day",
        "please i need something to drink now",
    ],
    "Mobility": [
        "i need help getting to the bathroom",
        "can someone help me stand up",
        "i want to get out of bed",
        "please help me walk to the toilet",
        "i cannot move on my own i need help",
        "help me sit up please",
        "i need to use the restroom can you assist",
        "can you bring me the wheelchair",
        "i need help turning over in bed",
        "please help me move to the chair",
        "i want to go for a short walk",
        "my legs are stuck help me move",
        "i need assistance to get up",
        "can someone help me lie down",
        "i need to go to the washroom",
        "help me reach my walker",
        "i am unable to get up by myself",
        "please help me change my position",
        "i need to stretch my legs can you help",
        "assist me to the bathroom please",
    ],
    "Hygiene": [
        "i need my bedsheets changed they are dirty",
        "can you help me take a bath",
        "i need to be cleaned up please",
        "my clothes are soiled please change them",
        "i would like to wash my hands",
        "can i get a fresh gown",
        "please help me brush my teeth",
        "the bed is wet please change it",
        "i need a sponge bath",
        "can you help me wash my face",
        "my diaper needs changing",
        "i want to freshen up",
        "please clean my room it smells",
        "i need help with my personal hygiene",
        "can you bring clean towels",
        "i spilled water on my sheets please change them",
        "help me clean up i had an accident",
        "i need a shower please",
        "my hands are dirty i need to wash",
        "please help me change into clean clothes",
    ],
    "Information": [
        "what time is it now",
        "when will the doctor come to see me",
        "what medication am i taking",
        "can you tell me my test results",
        "when is my surgery scheduled",
        "how long do i have to stay here",
        "what time are visiting hours",
        "can you explain what this medicine does",
        "when is my next appointment",
        "who is my nurse today",
        "what are these pills for",
        "can i know my blood pressure reading",
        "when can i go home",
        "what did the doctor say about my reports",
        "is my family allowed to visit now",
        "what time will i get my next dose",
        "can you tell me the day today",
        "how is my recovery going",
        "what should i eat with this medication",
        "when will my results be ready",
    ],
    "Other": [
        "can you turn off the lights please",
        "the tv remote is not working",
        "it is too cold can you adjust the ac",
        "can you open the window",
        "the room is too hot",
        "can you close the curtains",
        "my phone charger is not reaching",
        "can you pass me my glasses",
        "the call button is not working",
        "can you lower the bed",
        "i dropped my book can you pick it up",
        "please adjust my pillow",
        "the light is too bright",
        "can you bring me a blanket",
        "i need another pillow",
        "can you fix the tv channel",
        "please close the door it is noisy",
        "can you raise the head of the bed",
        "the fan is too strong please reduce it",
        "can you hand me the newspaper",
    ],
    # Reinforce the sparse real classes with clear nurse-call phrasings
    "Emergency": [
        "i cannot breathe please help",
        "help i am having chest pain",
        "i feel like i am going to faint",
        "call the doctor immediately",
        "i think i am having a heart attack",
        "i cannot feel my arm this is an emergency",
        "help me i am bleeding a lot",
        "i am choking please help now",
        "my chest is very tight i cannot breathe",
        "please hurry something is very wrong",
        "i can't breathe",
        "i am not able to breathe",
        "i am having trouble breathing",
        "it is hard to breathe",
        "i am short of breath",
        "my heart is racing i feel faint",
        "i am dizzy and about to collapse",
        "please help this is urgent",
        "i am gasping for air",
        "someone come quickly i need help now",
    ],
    "Emotional Support": [
        "i feel very scared and alone",
        "i am anxious can someone sit with me",
        "i feel like crying please stay",
        "i am worried about my condition",
        "i feel so depressed today",
        "please i just need someone to talk to",
        "i am frightened about the surgery",
        "i feel lonely can you stay a while",
        "i am very nervous right now",
        "i feel hopeless and sad",
    ],
    "Medication": [
        "i need my painkiller tablet",
        "can i have my medicine now",
        "it is time for my pills",
        "i missed my medication dose",
        "please bring my tablets",
        "i need my injection",
        "can i get my pain relief medication",
        "my medicine is due now",
        "i need something for the pain a tablet",
        "please give me my prescribed pills",
        "i have not taken my medicine yet",
        "can you bring my antibiotics",
        "i need my insulin shot",
        "it is time for my drops",
        "i want my headache tablet",
    ],
}


def get_augmentation_rows():
    """Return list of (text, intent) tuples for augmentation."""
    rows = []
    for intent, phrases in AUGMENTATION.items():
        if intent.endswith("_extra"):
            continue
        for p in phrases:
            rows.append((p, intent))
    return rows
