# -*- coding: utf-8 -*-
"""
trilingual_phrases.py — curated nurse-call phrases in English, Hindi (Devanagari),
and Kannada for all 9 CareVoice intents.

Used to train the multilingual intent classifier (distilbert-base-multilingual-cased)
so the system understands patient requests in all three languages. Each phrase is a
natural way a patient might voice that need; labels are guaranteed correct because
they're authored per-intent.
"""

# intent -> {language -> [phrases]}
TRILINGUAL = {
    "Emergency": {
        "en": [
            "i cannot breathe please help",
            "help i am having chest pain",
            "i feel like i am going to faint",
            "call the doctor immediately",
            "i think i am having a heart attack",
            "help me i am bleeding",
            "i am choking please help now",
            "my chest is very tight i cannot breathe",
            "please hurry something is very wrong",
            "i am not able to breathe",
        ],
        "hi": [
            "मुझे सांस नहीं आ रही है मदद करो",
            "मेरे सीने में बहुत दर्द हो रहा है",
            "मुझे लगता है मैं बेहोश हो जाऊँगा",
            "तुरंत डॉक्टर को बुलाओ",
            "मुझे दिल का दौरा पड़ रहा है",
            "मदद करो मुझे खून बह रहा है",
            "मेरा दम घुट रहा है जल्दी करो",
            "मेरी छाती जकड़ रही है साँस नहीं आ रही",
            "जल्दी करो कुछ गड़बड़ है",
            "मुझसे साँस नहीं ली जा रही",
        ],
        "kn": [
            "ನನಗೆ ಉಸಿರಾಡಲು ಆಗುತ್ತಿಲ್ಲ ಸಹಾಯ ಮಾಡಿ",
            "ನನ್ನ ಎದೆಯಲ್ಲಿ ತುಂಬಾ ನೋವಾಗುತ್ತಿದೆ",
            "ನಾನು ಮೂರ್ಛೆ ಹೋಗುತ್ತೇನೆ ಅನಿಸುತ್ತಿದೆ",
            "ತಕ್ಷಣ ವೈದ್ಯರನ್ನು ಕರೆಯಿರಿ",
            "ನನಗೆ ಹೃದಯಾಘಾತ ಆಗುತ್ತಿದೆ",
            "ಸಹಾಯ ಮಾಡಿ ನನಗೆ ರಕ್ತ ಸೋರುತ್ತಿದೆ",
            "ನನ್ನ ಉಸಿರು ಕಟ್ಟುತ್ತಿದೆ ಬೇಗ ಬನ್ನಿ",
            "ನನ್ನ ಎದೆ ಬಿಗಿಯಾಗಿದೆ ಉಸಿರಾಡಲು ಆಗುತ್ತಿಲ್ಲ",
            "ಬೇಗ ಬನ್ನಿ ಏನೋ ತಪ್ಪಾಗಿದೆ",
            "ನನಗೆ ಉಸಿರಾಡಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ",
        ],
        "de": [
            "ich bekomme keine Luft bitte helfen Sie",
            "ich habe starke Schmerzen in der Brust",
            "ich glaube ich werde ohnmächtig",
            "rufen Sie sofort den Arzt",
            "ich glaube ich habe einen Herzinfarkt",
            "helfen Sie mir ich blute stark",
            "ich ersticke bitte helfen Sie schnell",
            "meine Brust ist ganz eng ich kann nicht atmen",
            "bitte beeilen Sie sich etwas stimmt nicht",
            "ich kann nicht atmen",
        ],
    },
    "Pain": {
        "en": [
            "i have a bad pain in my knee",
            "my back is hurting a lot",
            "there is sharp pain in my stomach",
            "my head is aching",
            "i feel pain in my chest area",
            "my leg hurts when i move",
            "i have severe pain in my shoulder",
            "my whole body is aching",
            "there is pain in my neck",
            "my joints are paining",
        ],
        "hi": [
            "मेरे घुटने में बहुत दर्द है",
            "मेरी पीठ में बहुत दर्द हो रहा है",
            "मेरे पेट में तेज़ दर्द है",
            "मेरे सिर में दर्द हो रहा है",
            "मुझे सीने में दर्द महसूस हो रहा है",
            "हिलने पर मेरे पैर में दर्द होता है",
            "मेरे कंधे में तेज़ दर्द है",
            "मेरा पूरा शरीर दर्द कर रहा है",
            "मेरी गर्दन में दर्द है",
            "मेरे जोड़ों में दर्द हो रहा है",
        ],
        "kn": [
            "ನನ್ನ ಮೊಣಕಾಲಿನಲ್ಲಿ ತುಂಬಾ ನೋವಿದೆ",
            "ನನ್ನ ಬೆನ್ನಿನಲ್ಲಿ ತುಂಬಾ ನೋವಾಗುತ್ತಿದೆ",
            "ನನ್ನ ಹೊಟ್ಟೆಯಲ್ಲಿ ತೀವ್ರ ನೋವಿದೆ",
            "ನನ್ನ ತಲೆ ನೋಯುತ್ತಿದೆ",
            "ನನ್ನ ಎದೆಯ ಭಾಗದಲ್ಲಿ ನೋವಿದೆ",
            "ಚಲಿಸಿದಾಗ ನನ್ನ ಕಾಲು ನೋಯುತ್ತದೆ",
            "ನನ್ನ ಭುಜದಲ್ಲಿ ತೀವ್ರ ನೋವಿದೆ",
            "ನನ್ನ ಇಡೀ ದೇಹ ನೋಯುತ್ತಿದೆ",
            "ನನ್ನ ಕುತ್ತಿಗೆಯಲ್ಲಿ ನೋವಿದೆ",
            "ನನ್ನ ಕೀಲುಗಳಲ್ಲಿ ನೋವಾಗುತ್ತಿದೆ",
        ],
        "de": [
            "ich habe starke Schmerzen im Knie",
            "mein Rücken tut sehr weh",
            "ich habe stechende Schmerzen im Bauch",
            "mein Kopf tut weh",
            "ich spüre Schmerzen in der Brust",
            "mein Bein tut weh wenn ich mich bewege",
            "ich habe starke Schmerzen in der Schulter",
            "mein ganzer Körper tut weh",
            "ich habe Schmerzen im Nacken",
            "meine Gelenke schmerzen",
        ],
    },
    "Medication": {
        "en": [
            "i need my painkiller tablet",
            "can i have my medicine now",
            "it is time for my pills",
            "please bring my tablets",
            "i need my injection",
            "i have not taken my medicine yet",
            "can you bring my antibiotics",
            "i need my insulin",
            "please give me my prescribed pills",
            "my medicine is due now",
        ],
        "hi": [
            "मुझे दर्द की गोली चाहिए",
            "क्या मुझे अभी दवा मिल सकती है",
            "मेरी गोली का समय हो गया है",
            "कृपया मेरी गोलियाँ लाइए",
            "मुझे इंजेक्शन चाहिए",
            "मैंने अभी तक दवा नहीं ली है",
            "क्या आप मेरी एंटीबायोटिक ला सकते हैं",
            "मुझे इंसुलिन चाहिए",
            "कृपया मुझे मेरी दवा दीजिए",
            "मेरी दवा का समय हो गया है",
        ],
        "kn": [
            "ನನಗೆ ನೋವು ನಿವಾರಕ ಮಾತ್ರೆ ಬೇಕು",
            "ಈಗ ನನಗೆ ಔಷಧಿ ಸಿಗಬಹುದೇ",
            "ನನ್ನ ಮಾತ್ರೆಯ ಸಮಯವಾಗಿದೆ",
            "ದಯವಿಟ್ಟು ನನ್ನ ಮಾತ್ರೆಗಳನ್ನು ತನ್ನಿ",
            "ನನಗೆ ಚುಚ್ಚುಮದ್ದು ಬೇಕು",
            "ನಾನು ಇನ್ನೂ ಔಷಧಿ ತೆಗೆದುಕೊಂಡಿಲ್ಲ",
            "ನನ್ನ ಪ್ರತಿಜೀವಕ ಔಷಧಿ ತರಬಹುದೇ",
            "ನನಗೆ ಇನ್ಸುಲಿನ್ ಬೇಕು",
            "ದಯವಿಟ್ಟು ನನ್ನ ಔಷಧಿ ಕೊಡಿ",
            "ನನ್ನ ಔಷಧಿಯ ಸಮಯವಾಗಿದೆ",
        ],
        "de": [
            "ich brauche meine Schmerztablette",
            "kann ich jetzt meine Medizin bekommen",
            "es ist Zeit für meine Tabletten",
            "bitte bringen Sie meine Tabletten",
            "ich brauche meine Spritze",
            "ich habe meine Medizin noch nicht genommen",
            "können Sie mein Antibiotikum bringen",
            "ich brauche mein Insulin",
            "bitte geben Sie mir meine verschriebenen Tabletten",
            "meine Medizin ist jetzt fällig",
        ],
    },
    "Food/Water": {
        "en": [
            "i am hungry can i get something to eat",
            "could i please have a glass of water",
            "i am really thirsty",
            "when is my next meal",
            "please bring me something to drink",
            "i would like some food",
            "my mouth is dry i need water",
            "i have not eaten all day",
            "can i get some juice",
            "please refill my water jug",
        ],
        "hi": [
            "मुझे भूख लगी है कुछ खाने को मिल सकता है",
            "कृपया मुझे एक गिलास पानी दीजिए",
            "मुझे बहुत प्यास लगी है",
            "मेरा अगला भोजन कब आएगा",
            "कृपया मुझे कुछ पीने को लाइए",
            "मुझे कुछ खाना चाहिए",
            "मेरा मुँह सूख रहा है मुझे पानी चाहिए",
            "मैंने पूरे दिन कुछ नहीं खाया",
            "क्या मुझे थोड़ा जूस मिल सकता है",
            "कृपया मेरा पानी का जग भर दीजिए",
        ],
        "kn": [
            "ನನಗೆ ಹಸಿವಾಗಿದೆ ತಿನ್ನಲು ಏನಾದರೂ ಸಿಗಬಹುದೇ",
            "ದಯವಿಟ್ಟು ನನಗೆ ಒಂದು ಲೋಟ ನೀರು ಕೊಡಿ",
            "ನನಗೆ ತುಂಬಾ ಬಾಯಾರಿಕೆಯಾಗಿದೆ",
            "ನನ್ನ ಮುಂದಿನ ಊಟ ಯಾವಾಗ",
            "ದಯವಿಟ್ಟು ಕುಡಿಯಲು ಏನಾದರೂ ತನ್ನಿ",
            "ನನಗೆ ಸ್ವಲ್ಪ ಆಹಾರ ಬೇಕು",
            "ನನ್ನ ಬಾಯಿ ಒಣಗಿದೆ ನನಗೆ ನೀರು ಬೇಕು",
            "ನಾನು ದಿನವಿಡೀ ಏನೂ ತಿಂದಿಲ್ಲ",
            "ನನಗೆ ಸ್ವಲ್ಪ ಜ್ಯೂಸ್ ಸಿಗಬಹುದೇ",
            "ದಯವಿಟ್ಟು ನನ್ನ ನೀರಿನ ಜಗ್ ತುಂಬಿಸಿ",
        ],
        "de": [
            "ich habe Hunger kann ich etwas zu essen bekommen",
            "könnte ich bitte ein Glas Wasser haben",
            "ich habe wirklich Durst",
            "wann gibt es meine nächste Mahlzeit",
            "bitte bringen Sie mir etwas zu trinken",
            "ich hätte gerne etwas zu essen",
            "mein Mund ist trocken ich brauche Wasser",
            "ich habe den ganzen Tag nichts gegessen",
            "kann ich etwas Saft bekommen",
            "bitte füllen Sie meinen Wasserkrug nach",
        ],
    },
    "Mobility": {
        "en": [
            "i need help getting to the bathroom",
            "can someone help me stand up",
            "i want to get out of bed",
            "please help me walk to the toilet",
            "i cannot move on my own",
            "help me sit up please",
            "can you bring me the wheelchair",
            "i need help turning over in bed",
            "please help me move to the chair",
            "i need to use the restroom",
        ],
        "hi": [
            "मुझे बाथरूम जाने में मदद चाहिए",
            "क्या कोई मुझे खड़े होने में मदद करेगा",
            "मुझे बिस्तर से उठना है",
            "कृपया मुझे शौचालय तक चलने में मदद करो",
            "मैं खुद से हिल नहीं सकता",
            "कृपया मुझे बैठने में मदद करो",
            "क्या आप मेरे लिए व्हीलचेयर ला सकते हैं",
            "मुझे बिस्तर पर करवट लेने में मदद चाहिए",
            "कृपया मुझे कुर्सी तक ले जाओ",
            "मुझे शौचालय जाना है",
        ],
        "kn": [
            "ನನಗೆ ಶೌಚಾಲಯಕ್ಕೆ ಹೋಗಲು ಸಹಾಯ ಬೇಕು",
            "ಯಾರಾದರೂ ನನಗೆ ಎದ್ದೇಳಲು ಸಹಾಯ ಮಾಡಿ",
            "ನಾನು ಹಾಸಿಗೆಯಿಂದ ಏಳಬೇಕು",
            "ದಯವಿಟ್ಟು ಶೌಚಾಲಯಕ್ಕೆ ನಡೆಯಲು ಸಹಾಯ ಮಾಡಿ",
            "ನಾನು ಸ್ವಂತವಾಗಿ ಚಲಿಸಲು ಆಗುತ್ತಿಲ್ಲ",
            "ದಯವಿಟ್ಟು ನನಗೆ ಕುಳಿತುಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡಿ",
            "ನನಗೆ ಗಾಲಿಕುರ್ಚಿ ತರಬಹುದೇ",
            "ಹಾಸಿಗೆಯಲ್ಲಿ ತಿರುಗಲು ನನಗೆ ಸಹಾಯ ಬೇಕು",
            "ದಯವಿಟ್ಟು ನನ್ನನ್ನು ಕುರ್ಚಿಗೆ ಸಾಗಿಸಿ",
            "ನಾನು ಶೌಚಾಲಯ ಬಳಸಬೇಕು",
        ],
        "de": [
            "ich brauche Hilfe um zur Toilette zu kommen",
            "kann mir jemand beim Aufstehen helfen",
            "ich möchte aus dem Bett aufstehen",
            "bitte helfen Sie mir zur Toilette zu gehen",
            "ich kann mich nicht alleine bewegen",
            "helfen Sie mir bitte beim Aufsetzen",
            "können Sie mir den Rollstuhl bringen",
            "ich brauche Hilfe mich im Bett umzudrehen",
            "bitte helfen Sie mir zum Stuhl zu kommen",
            "ich muss auf die Toilette",
        ],
    },
    "Hygiene": {
        "en": [
            "i need my bedsheets changed they are dirty",
            "can you help me take a bath",
            "i need to be cleaned up",
            "my clothes are soiled please change them",
            "i would like to wash my hands",
            "please help me brush my teeth",
            "the bed is wet please change it",
            "i need a sponge bath",
            "my diaper needs changing",
            "please help me change into clean clothes",
        ],
        "hi": [
            "मेरी चादर गंदी है इसे बदल दीजिए",
            "क्या आप मुझे नहाने में मदद करेंगे",
            "मुझे साफ करने की जरूरत है",
            "मेरे कपड़े गंदे हैं कृपया बदल दीजिए",
            "मैं अपने हाथ धोना चाहता हूँ",
            "कृपया मुझे दाँत साफ करने में मदद करो",
            "बिस्तर गीला है कृपया बदल दीजिए",
            "मुझे स्पंज बाथ चाहिए",
            "मेरा डायपर बदलने की जरूरत है",
            "कृपया मुझे साफ कपड़े पहनने में मदद करो",
        ],
        "kn": [
            "ನನ್ನ ಹಾಸಿಗೆ ಹೊದಿಕೆ ಕೊಳಕಾಗಿದೆ ಬದಲಾಯಿಸಿ",
            "ಸ್ನಾನ ಮಾಡಲು ನನಗೆ ಸಹಾಯ ಮಾಡುವಿರಾ",
            "ನನ್ನನ್ನು ಸ್ವಚ್ಛಗೊಳಿಸಬೇಕು",
            "ನನ್ನ ಬಟ್ಟೆ ಕೊಳಕಾಗಿದೆ ದಯವಿಟ್ಟು ಬದಲಾಯಿಸಿ",
            "ನಾನು ಕೈ ತೊಳೆಯಬೇಕು",
            "ದಯವಿಟ್ಟು ಹಲ್ಲು ಉಜ್ಜಲು ಸಹಾಯ ಮಾಡಿ",
            "ಹಾಸಿಗೆ ಒದ್ದೆಯಾಗಿದೆ ದಯವಿಟ್ಟು ಬದಲಾಯಿಸಿ",
            "ನನಗೆ ಸ್ಪಂಜ್ ಸ್ನಾನ ಬೇಕು",
            "ನನ್ನ ಡಯಾಪರ್ ಬದಲಾಯಿಸಬೇಕು",
            "ಸ್ವಚ್ಛ ಬಟ್ಟೆ ಧರಿಸಲು ಸಹಾಯ ಮಾಡಿ",
        ],
        "de": [
            "meine Bettwäsche ist schmutzig bitte wechseln Sie sie",
            "können Sie mir beim Baden helfen",
            "ich muss sauber gemacht werden",
            "meine Kleidung ist beschmutzt bitte wechseln Sie sie",
            "ich möchte meine Hände waschen",
            "bitte helfen Sie mir beim Zähneputzen",
            "das Bett ist nass bitte wechseln Sie es",
            "ich brauche eine Waschung im Bett",
            "meine Windel muss gewechselt werden",
            "bitte helfen Sie mir in saubere Kleidung",
        ],
    },
    "Information": {
        "en": [
            "what time is it now",
            "when will the doctor come",
            "what medication am i taking",
            "can you tell me my test results",
            "when is my surgery scheduled",
            "how long do i have to stay here",
            "when can i go home",
            "who is my nurse today",
            "when is my next appointment",
            "what are these pills for",
        ],
        "hi": [
            "अभी क्या समय हुआ है",
            "डॉक्टर कब आएंगे",
            "मैं कौन सी दवा ले रहा हूँ",
            "क्या आप मुझे मेरी जाँच के नतीजे बता सकते हैं",
            "मेरा ऑपरेशन कब है",
            "मुझे यहाँ कितने दिन रहना है",
            "मैं घर कब जा सकता हूँ",
            "आज मेरी नर्स कौन है",
            "मेरी अगली अपॉइंटमेंट कब है",
            "ये गोलियाँ किस लिए हैं",
        ],
        "kn": [
            "ಈಗ ಸಮಯ ಎಷ್ಟು",
            "ವೈದ್ಯರು ಯಾವಾಗ ಬರುತ್ತಾರೆ",
            "ನಾನು ಯಾವ ಔಷಧಿ ತೆಗೆದುಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ",
            "ನನ್ನ ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶ ಹೇಳಬಹುದೇ",
            "ನನ್ನ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ ಯಾವಾಗ",
            "ನಾನು ಇಲ್ಲಿ ಎಷ್ಟು ದಿನ ಇರಬೇಕು",
            "ನಾನು ಮನೆಗೆ ಯಾವಾಗ ಹೋಗಬಹುದು",
            "ಇಂದು ನನ್ನ ದಾದಿ ಯಾರು",
            "ನನ್ನ ಮುಂದಿನ ಭೇಟಿ ಯಾವಾಗ",
            "ಈ ಮಾತ್ರೆಗಳು ಯಾವುದಕ್ಕೆ",
        ],
        "de": [
            "wie spät ist es jetzt",
            "wann kommt der Arzt",
            "welche Medikamente nehme ich",
            "können Sie mir meine Testergebnisse sagen",
            "wann ist meine Operation geplant",
            "wie lange muss ich hier bleiben",
            "wann kann ich nach Hause gehen",
            "wer ist heute meine Pflegekraft",
            "wann ist mein nächster Termin",
            "wofür sind diese Tabletten",
        ],
    },
    "Emotional Support": {
        "en": [
            "i feel very scared and alone",
            "i am anxious can someone sit with me",
            "i feel like crying please stay",
            "i am worried about my condition",
            "i feel so depressed today",
            "please i just need someone to talk to",
            "i am frightened about the surgery",
            "i feel lonely can you stay a while",
            "i am very nervous right now",
            "i feel hopeless and sad",
        ],
        "hi": [
            "मुझे बहुत डर लग रहा है और मैं अकेला हूँ",
            "मैं घबराया हुआ हूँ कोई मेरे पास बैठे",
            "मेरा रोने का मन कर रहा है कृपया रुको",
            "मुझे अपनी हालत की चिंता है",
            "आज मैं बहुत उदास महसूस कर रहा हूँ",
            "कृपया मुझे किसी से बात करनी है",
            "मुझे ऑपरेशन से डर लग रहा है",
            "मुझे अकेलापन लग रहा है कुछ देर रुको",
            "मैं अभी बहुत घबराया हुआ हूँ",
            "मुझे निराशा और दुख महसूस हो रहा है",
        ],
        "kn": [
            "ನನಗೆ ತುಂಬಾ ಭಯ ಮತ್ತು ಒಂಟಿತನ ಅನಿಸುತ್ತಿದೆ",
            "ನಾನು ಆತಂಕಗೊಂಡಿದ್ದೇನೆ ಯಾರಾದರೂ ನನ್ನ ಜೊತೆ ಕುಳಿತುಕೊಳ್ಳಿ",
            "ನನಗೆ ಅಳು ಬರುತ್ತಿದೆ ದಯವಿಟ್ಟು ಇರಿ",
            "ನನ್ನ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ಚಿಂತೆಯಾಗಿದೆ",
            "ಇಂದು ನಾನು ತುಂಬಾ ಖಿನ್ನನಾಗಿದ್ದೇನೆ",
            "ದಯವಿಟ್ಟು ನನಗೆ ಯಾರೊಂದಿಗಾದರೂ ಮಾತನಾಡಬೇಕು",
            "ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಯ ಬಗ್ಗೆ ನನಗೆ ಭಯವಾಗಿದೆ",
            "ನನಗೆ ಒಂಟಿತನ ಅನಿಸುತ್ತಿದೆ ಸ್ವಲ್ಪ ಹೊತ್ತು ಇರಿ",
            "ನಾನು ಈಗ ತುಂಬಾ ಆತಂಕದಲ್ಲಿದ್ದೇನೆ",
            "ನನಗೆ ನಿರಾಶೆ ಮತ್ತು ದುಃಖ ಅನಿಸುತ್ತಿದೆ",
        ],
        "de": [
            "ich fühle mich sehr ängstlich und allein",
            "ich bin unruhig kann jemand bei mir sitzen",
            "mir ist zum Weinen bitte bleiben Sie",
            "ich mache mir Sorgen um meinen Zustand",
            "ich fühle mich heute so niedergeschlagen",
            "bitte ich brauche einfach jemanden zum Reden",
            "ich habe Angst vor der Operation",
            "ich fühle mich einsam können Sie eine Weile bleiben",
            "ich bin gerade sehr nervös",
            "ich fühle mich hoffnungslos und traurig",
        ],
    },
    "Other": {
        "en": [
            "can you turn off the lights please",
            "it is too cold can you adjust the ac",
            "can you open the window",
            "please adjust my pillow",
            "can you bring me a blanket",
            "the room is too hot",
            "please close the door it is noisy",
            "can you pass me my glasses",
            "i need another pillow",
            "can you raise the head of the bed",
        ],
        "hi": [
            "कृपया लाइट बंद कर दीजिए",
            "बहुत ठंड है कृपया एसी ठीक कर दीजिए",
            "क्या आप खिड़की खोल सकते हैं",
            "कृपया मेरा तकिया ठीक कर दीजिए",
            "क्या आप मुझे एक कंबल ला सकते हैं",
            "कमरा बहुत गर्म है",
            "कृपया दरवाज़ा बंद कर दीजिए शोर है",
            "क्या आप मुझे मेरा चश्मा दे सकते हैं",
            "मुझे एक और तकिया चाहिए",
            "क्या आप बिस्तर का सिरहाना ऊँचा कर सकते हैं",
        ],
        "kn": [
            "ದಯವಿಟ್ಟು ದೀಪ ಆರಿಸಿ",
            "ತುಂಬಾ ಚಳಿಯಿದೆ ದಯವಿಟ್ಟು ಎಸಿ ಸರಿಪಡಿಸಿ",
            "ಕಿಟಕಿ ತೆರೆಯಬಹುದೇ",
            "ದಯವಿಟ್ಟು ನನ್ನ ದಿಂಬು ಸರಿಪಡಿಸಿ",
            "ನನಗೆ ಒಂದು ಹೊದಿಕೆ ತರಬಹುದೇ",
            "ಕೋಣೆ ತುಂಬಾ ಬಿಸಿಯಾಗಿದೆ",
            "ದಯವಿಟ್ಟು ಬಾಗಿಲು ಮುಚ್ಚಿ ಗದ್ದಲವಿದೆ",
            "ನನ್ನ ಕನ್ನಡಕ ಕೊಡಬಹುದೇ",
            "ನನಗೆ ಇನ್ನೊಂದು ದಿಂಬು ಬೇಕು",
            "ಹಾಸಿಗೆಯ ತಲೆಭಾಗ ಎತ್ತರಿಸಬಹುದೇ",
        ],
        "de": [
            "können Sie bitte das Licht ausschalten",
            "es ist zu kalt können Sie die Klimaanlage einstellen",
            "können Sie das Fenster öffnen",
            "bitte richten Sie mein Kissen",
            "können Sie mir eine Decke bringen",
            "das Zimmer ist zu heiß",
            "bitte schließen Sie die Tür es ist laut",
            "können Sie mir meine Brille reichen",
            "ich brauche noch ein Kissen",
            "können Sie das Kopfende des Bettes anheben",
        ],
    },
}


def get_trilingual_rows():
    """Return list of (text, intent, language) tuples."""
    rows = []
    for intent, langs in TRILINGUAL.items():
        for lang, phrases in langs.items():
            for p in phrases:
                rows.append((p, intent, lang))
    return rows
